import { Component, input, output } from '@angular/core';

import { AgentTrace } from '../../../shared/agent-trace';
import type { ModelDoc } from '../../../api/model/modelDoc';
import { sourceHost, summarySections } from '../summary';

/** The About tab: the web-researched summary, and where it starts from nothing. */
import { RerunButton } from '../../../shared/rerun-button';

@Component({
  selector: 'app-about-tab',
  imports: [RerunButton, AgentTrace],
  template: `
    <section class="pane">
      <!-- The agent's thinking sits with what it wrote. Above the tabs it was a
           wall of two interleaved traces on every tab. -->
      <app-agent-trace [only]="modelId()" agent="about" />
      @if (model().summary; as summary) {
        <p class="overview">{{ summary.overview }}</p>

        <div class="sections">
          @for (section of summarySections(summary); track section.label) {
            <div class="sum-section">
              <h3>{{ section.label }}</h3>
              @if (section.items.length) {
                <ul>
                  @for (item of section.items; track item) {
                    <li>{{ item }}</li>
                  }
                </ul>
              } @else {
                <!-- Kept rather than hidden: a thin summary must not read like
                     a complete one. -->
                <p class="none">none stated</p>
              }
            </div>
          }
        </div>

        <p class="prov">
          generated by <code>{{ summary.generated_by }}</code> on {{ summary.generated_on }}
          @if (summary.sources?.length) {
            · sources
            @for (url of summary.sources; track url) {
              <a [href]="url" target="_blank" rel="noopener noreferrer">{{ sourceHost(url) }}</a>
            }
          } @else {
            · no web sources; written from the card alone
          }
        </p>

        <app-rerun-button
          agent="about"
          label="Regenerate"
          [busy]="busy()"
          (rerun)="rerun.emit($event)"
        />
      } @else if (!summarising()) {
        <div class="cta">
          <p>Nobody has summarised this model yet.</p>
          <button (click)="summarise.emit(model().model_id)">Generate summary</button>
        </div>
      }
      @if (summarising()) {
        <div class="bar"><span></span></div>
        <p class="hint">Searching the web and writing. About a minute.</p>
      }
    </section>
  `,
  styles: `
    .pane {
      padding-top: var(--space-4);
    }

    .overview {
      margin: 0 0 var(--space-6);
      font-size: 1rem;
      line-height: 1.6;
      max-width: 62ch;
    }
    .sections {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(20rem, 1fr));
      gap: var(--space-4);
    }
    .sum-section {
      padding: var(--space-4);
      background: var(--sheet-sunken);
      border-radius: var(--radius-sm);
    }
    .sum-section h3 {
      margin: 0 0 var(--space-2);
      font-size: 0.7rem;
      font-weight: 700;
      text-transform: uppercase;
      letter-spacing: 0.05em;
      color: var(--sheet-faint);
    }
    .sum-section ul {
      margin: 0;
      padding-left: 1.1rem;
    }
    .sum-section li {
      font-size: 0.88rem;
      line-height: 1.5;
      margin-bottom: 0.3rem;
    }

    .hint,
    .prov,
    .none {
      font-size: 0.78rem;
      color: var(--sheet-muted);
    }
    .hint {
      margin: 0 0 var(--space-3);
    }
    .prov {
      margin: var(--space-4) 0 var(--space-3);
    }
    .none {
      margin: 0;
      font-style: italic;
    }
    code {
      background: var(--sheet-sunken);
      padding: 0.05rem 0.3rem;
      border-radius: 4px;
    }
    .prov a {
      margin-left: var(--space-2);
      color: var(--tone);
      text-decoration: underline;
    }
    .cta {
      display: flex;
      gap: var(--space-4);
      align-items: center;
      flex-wrap: wrap;
      padding: var(--space-4);
      border: 1px dashed var(--sheet-border);
      border-radius: var(--radius-sm);
      color: var(--sheet-muted);
    }
    .pane button {
      background: var(--tone);
      color: #fff;
      border: none;
    }
    .pane button:hover:not(:disabled) {
      filter: brightness(1.08);
    }
    button.ghost {
      margin-top: var(--space-4);
      background: none;
      border: 1px solid var(--sheet-border);
      color: var(--sheet-muted);
      font-size: 0.78rem;
      padding: 0.3rem 0.7rem;
    }
    button.ghost:hover:not(:disabled) {
      filter: none;
      color: var(--sheet-fg);
      border-color: var(--sheet-faint);
    }
  `,
})
export class AboutTab {
  readonly model = input.required<ModelDoc>();
  readonly modelId = input.required<string>();
  readonly busy = input.required<boolean>();
  readonly summarising = input.required<boolean>();
  readonly rerun = output<string>();
  readonly summarise = output<string>();

  protected readonly summarySections = summarySections;
  protected readonly sourceHost = sourceHost;
}
