/**
 * Generated by orval 🍺
 * Do not edit manually.
 * llmdex
 * OpenAPI spec version: 0.1.0
 */
import type { ChatRequestHistoryItem } from './chatRequestHistoryItem';

export interface ChatRequest {
  /** @minLength 1 */
  message: string;
  history?: ChatRequestHistoryItem[];
}
