/**
 * Generated by orval 🍺
 * Do not edit manually.
 * llmdex
 * OpenAPI spec version: 0.1.0
 */
import type { BenchmarkScore } from './benchmarkScore';
import type { Derived } from './derived';
import type { Extracted } from './extracted';
import type { Manual } from './manual';
import type { Measured } from './measured';

/**
 * R4.1 - one artifact of a model: a specific quantization, in a specific repo.
 */
export interface Checkpoint {
  repo: string;
  quantization?: string | null;
  card_revision?: string | null;
  ingested?: string | null;
  derived?: Derived | null;
  extracted?: Extracted | null;
  manual?: Manual;
  benchmarks?: BenchmarkScore[];
  measured?: Measured[];
}
