/**
 * Generated by orval 🍺
 * Do not edit manually.
 * llmdex
 * OpenAPI spec version: 0.1.0
 */
import type { HeadDim } from './headDim';
import type { LayerComposition } from './layerComposition';
import type { ParamCounts } from './paramCounts';
import type { VRAMEstimate } from './vRAMEstimate';
import type { WeightBytes } from './weightBytes';

/**
 * R2.1 - fields computed from structured files. Never a guess.
 */
export interface Derived {
  architecture?: string | null;
  architecture_class?: string | null;
  hidden_size?: number | null;
  num_hidden_layers?: number | null;
  num_attention_heads?: number | null;
  num_key_value_heads?: number | null;
  head_dim?: HeadDim;
  vocab_size?: number | null;
  context_length?: number | null;
  torch_dtype?: string | null;
  layers?: LayerComposition;
  params?: ParamCounts;
  weights?: WeightBytes;
  vram?: VRAMEstimate | null;
  underivable?: string[];
}
