/**
 * Generated by orval 🍺
 * Do not edit manually.
 * llmdex
 * OpenAPI spec version: 0.1.0
 */

export interface DriftReport {
  model_id: string;
  stored_revision: string | null;
  upstream_revision: string | null;
  drifted: boolean;
}
