/**
 * Generated by orval 🍺
 * Do not edit manually.
 * llmdex
 * OpenAPI spec version: 0.1.0
 */
import type { ExtractedBenchmark } from './extractedBenchmark';
import type { ExtractedQuantization } from './extractedQuantization';
import type { ExtractedServing } from './extractedServing';
import type { RejectedValue } from './rejectedValue';

/**
 * R3.x - what a language model found in the card, after verification.
 *
 * ``card_revision`` is carried here rather than borrowed from ingest because a
 * span is only meaningful against one specific text. If the card moves, these
 * offsets describe the revision this block names, not the current one.
 */
export interface Extracted {
  card_revision: string;
  extracted_on: string;
  model: string;
  quantization?: ExtractedQuantization | null;
  serving?: ExtractedServing | null;
  benchmarks?: ExtractedBenchmark[];
  rejected?: RejectedValue[];
}
