/**
 * Generated by orval 🍺
 * Do not edit manually.
 * llmdex
 * OpenAPI spec version: 0.1.0
 */
import type { Span } from './span';

/**
 * R3.4 - the same four fields as ``Quantization``, each as a verified span.
 */
export interface ExtractedQuantization {
  format?: Span | null;
  method?: Span | null;
  scope?: Span | null;
  calibration?: Span | null;
}
