/**
 * Generated by orval 🍺
 * Do not edit manually.
 * llmdex
 * OpenAPI spec version: 0.1.0
 */
import type { ExtractedServingEngines } from './extractedServingEngines';

export interface ExtractedServing {
  engines?: ExtractedServingEngines;
}
