/**
 * Generated by orval 🍺
 * Do not edit manually.
 * llmdex
 * OpenAPI spec version: 0.1.0
 */

export type HeadDimSource = (typeof HeadDimSource)[keyof typeof HeadDimSource] | null;

export const HeadDimSource = {
  explicit: 'explicit',
  derived: 'derived',
} as const;
