/**
 * Generated by orval 🍺
 * Do not edit manually.
 * llmdex
 * OpenAPI spec version: 0.1.0
 */

/**
 * R2.4a - config states one head_dim, hidden/heads implies another.
 */
export interface HeadDimMismatch {
  explicit: number;
  derived: number;
}
