/**
 * Generated by orval 🍺
 * Do not edit manually.
 * llmdex
 * OpenAPI spec version: 0.1.0
 */

export type LayerCompositionFamily = typeof LayerCompositionFamily[keyof typeof LayerCompositionFamily];


export const LayerCompositionFamily = {
  transformer: 'transformer',
  nemotron_h: 'nemotron_h',
  jamba: 'jamba',
  hybrid: 'hybrid',
  recurrent: 'recurrent',
  unknown: 'unknown',
} as const;
