/**
 * Generated by orval 🍺
 * Do not edit manually.
 * llmdex
 * OpenAPI spec version: 0.1.0
 */
import type { LayerCompositionFamily } from './layerCompositionFamily';

/**
 * How many layers of each kind. R2.6a - never assume a fixed ratio.
 */
export interface LayerComposition {
  family?: LayerCompositionFamily;
  attention?: number;
  recurrent?: number;
  mlp_only?: number;
  unreliable_reason?: string | null;
}
