/**
 * Generated by orval 🍺
 * Do not edit manually.
 * llmdex
 * OpenAPI spec version: 0.1.0
 */
import type { Quantization } from './quantization';
import type { Serving } from './serving';

/**
 * R6.5 - hand-entered prose. Ingest never writes here.
 *
 * ``reviewed`` separates two of R6.4's four states. Null means nobody has read
 * the card, so a null field below it is unknown. Set means a person read it, so
 * a null field below it is genuinely absent from the card.
 *
 * ``extra="forbid"`` matters because this block is edited by hand: Pydantic's
 * default would drop a mistyped key silently and the next write would erase it.
 */
export interface Manual {
  reviewed?: string | null;
  quantization?: Quantization | null;
  serving?: Serving | null;
}
