/**
 * Generated by orval 🍺
 * Do not edit manually.
 * llmdex
 * OpenAPI spec version: 0.1.0
 */

/**
 * R4.2 / R4.3 - numbers the team produces. Ingest never writes these.
 *
 * Hardware and serving configuration are required, not optional context. A
 * throughput figure without them describes nothing anyone can act on, so a
 * partial entry is rejected rather than stored.
 */
export interface Measured {
  /** @minLength 1 */
  hardware: string;
  /** @minLength 1 */
  serving: string;
  ttft_ms?: number | null;
  itl_ms?: number | null;
  throughput_tok_s?: number | null;
  peak_vram_bytes?: number | null;
  measured_on?: string | null;
  notes?: string | null;
}
