/**
 * Generated by orval 🍺
 * Do not edit manually.
 * llmdex
 * OpenAPI spec version: 0.1.0
 */
import type { Checkpoint } from './checkpoint';
import type { Summary } from './summary';

/**
 * R4.1 - shared identity; everything that varies by artifact lives on checkpoints.
 */
export interface ModelDoc {
  model_id: string;
  name?: string | null;
  vendor?: string | null;
  released?: string | null;
  summary?: Summary | null;
  checkpoints?: Checkpoint[];
}
