/**
 * Generated by orval 🍺
 * Do not edit manually.
 * llmdex
 * OpenAPI spec version: 0.1.0
 */

export interface ParamCounts {
  total?: number | null;
  active?: number | null;
  is_moe?: boolean;
}
