/**
 * Generated by orval 🍺
 * Do not edit manually.
 * llmdex
 * OpenAPI spec version: 0.1.0
 */

/**
 * R3.4 - the quantization recipe, copied from the card by hand.
 *
 * ``src`` is required (R3.3). A recipe with no pointer at the section it came
 * from cannot be re-checked when the card changes underneath it, and an
 * unauditable value is the thing this project exists to not produce.
 */
export interface Quantization {
  format?: string | null;
  method?: string | null;
  scope?: string | null;
  calibration?: string | null;
  /** @minLength 1 */
  src: string;
}
