/**
 * Generated by orval 🍺
 * Do not edit manually.
 * llmdex
 * OpenAPI spec version: 0.1.0
 */

export type RejectedValueReason = typeof RejectedValueReason[keyof typeof RejectedValueReason];


export const RejectedValueReason = {
  no_match: 'no_match',
  empty: 'empty',
  not_contiguous: 'not_contiguous',
} as const;
