/**
 * Generated by orval 🍺
 * Do not edit manually.
 * llmdex
 * OpenAPI spec version: 0.1.0
 */
import type { RejectedValueReason } from './rejectedValueReason';

/**
 * R3.2 - what the model claimed, and why it was not stored.
 *
 * A bare null would lose the fact that the model produced something. This is
 * where invention becomes visible, and it is the main evidence for whether an
 * endpoint can be trusted with this job at all.
 */
export interface RejectedValue {
  field: string;
  proposed: string;
  reason: RejectedValueReason;
}
