/**
 * Generated by orval 🍺
 * Do not edit manually.
 * llmdex
 * OpenAPI spec version: 0.1.0
 */
import type { ServingEngines } from './servingEngines';

/**
 * R3.4 - per-engine support with version pins, exactly as the card states them.
 *
 * Values stay strings because a card pins a version (``"0.27.1"``) or states a
 * condition (``"dev container only"``). Both are facts worth keeping; parsing
 * would force the second into a shape it does not have.
 */
export interface Serving {
  engines: ServingEngines;
  /** @minLength 1 */
  src: string;
}
