/**
 * Generated by orval 🍺
 * Do not edit manually.
 * llmdex
 * OpenAPI spec version: 0.1.0
 */

/**
 * A verified quote and where it was found in the card.
 *
 * Constructed only after :mod:`backend.extraction.ground` has matched the quote
 * against the source, which is why every field is required. ``text`` is sliced
 * out of the card rather than copied from the model's response -- the model
 * locates, it does not supply (R3.1).
 */
export interface Span {
  text: string;
  start: number;
  end: number;
  section: string;
  occurrences?: number;
}
