/**
 * Generated by orval 🍺
 * Do not edit manually.
 * llmdex
 * OpenAPI spec version: 0.1.0
 */

export type StreamAgentsModelsModelIdAgentsStreamGetParams = {
  /**
   * comma-separated agent names
   */
  agents?: string;
};
