/**
 * Generated by orval 🍺
 * Do not edit manually.
 * llmdex
 * OpenAPI spec version: 0.1.0
 */

/**
 * A written account of what the model is, generated rather than copied.
 *
 * This is the one block in the system that is not quoted from somewhere. It
 * exists because the copy-only rule (R3.1), correct for a specification sheet,
 * cannot answer "what is this model good for" -- no card states its own cons.
 * It is therefore held to a different discipline: not verbatim, but sourced,
 * dated, attributed to the endpoint that wrote it, and regenerable.
 *
 * It lives on the model rather than the checkpoint because the card and the
 * facts it draws on do not vary by quantization: an AWQ build and a GGUF build
 * of one model are the same model to a reader asking what it is for.
 */
export interface Summary {
  /** @minLength 1 */
  overview: string;
  unique_points?: string[];
  pros?: string[];
  cons?: string[];
  use_cases?: string[];
  sources?: string[];
  generated_by: string;
  generated_on: string;
}
