/**
 * Generated by orval 🍺
 * Do not edit manually.
 * llmdex
 * OpenAPI spec version: 0.1.0
 */
import type { VRAMAssumptionsKvDtype } from './vRAMAssumptionsKvDtype';

/**
 * R2.5 - an estimate without these is not acceptable output.
 */
export interface VRAMAssumptions {
  context: number;
  batch?: number;
  kv_dtype?: VRAMAssumptionsKvDtype;
  overhead_bytes?: number;
}
