/**
 * Generated by orval 🍺
 * Do not edit manually.
 * llmdex
 * OpenAPI spec version: 0.1.0
 */

export type VRAMAssumptionsKvDtype = typeof VRAMAssumptionsKvDtype[keyof typeof VRAMAssumptionsKvDtype];


export const VRAMAssumptionsKvDtype = {
  fp32: 'fp32',
  fp16: 'fp16',
  bf16: 'bf16',
  fp8: 'fp8',
  int8: 'int8',
} as const;
