/**
 * Generated by orval 🍺
 * Do not edit manually.
 * llmdex
 * OpenAPI spec version: 0.1.0
 */
import type { VRAMAssumptions } from './vRAMAssumptions';

export interface VRAMEstimate {
  total_bytes?: number | null;
  weight_bytes?: number | null;
  kv_cache_bytes?: number | null;
  assumptions: VRAMAssumptions;
  unreliable_reason?: string | null;
}
