/**
 * Generated by orval 🍺
 * Do not edit manually.
 * llmdex
 * OpenAPI spec version: 0.1.0
 */

export interface WeightBytes {
  bytes?: number | null;
  file_count?: number;
  estimated?: boolean;
  unreliable_reason?: string | null;
}
