/**
 * Generated by orval 🍺
 * Do not edit manually.
 * llmdex
 * OpenAPI spec version: 0.1.0
 */
import {
  HttpClient,
  HttpHeaders,
  HttpResponse as AngularHttpResponse
} from '@angular/common/http';
import type {
  HttpContext,
  HttpEvent,
  HttpParams
} from '@angular/common/http';

import {
  Injectable,
  inject
} from '@angular/core';

import {
  Observable
} from 'rxjs';

import type {
  Benchmark,
  DriftReport,
  Health,
  IngestRequest,
  ModelDoc
} from './model';



interface HttpClientOptions {
  readonly headers?: HttpHeaders | Record<string, string | string[]>;
  readonly context?: HttpContext;
  readonly params?:
        | HttpParams
      | Record<string, string | number | boolean | Array<string | number | boolean>>;
  readonly reportProgress?: boolean;
  readonly withCredentials?: boolean;
  readonly credentials?: RequestCredentials;
  readonly keepalive?: boolean;
  readonly priority?: RequestPriority;
  readonly cache?: RequestCache;
  readonly mode?: RequestMode;
  readonly redirect?: RequestRedirect;
  readonly referrer?: string;
  readonly integrity?: string;
  readonly referrerPolicy?: ReferrerPolicy;
  readonly transferCache?: {includeHeaders?: string[]} | boolean;
  readonly timeout?: number;
}

type HttpClientBodyOptions = HttpClientOptions & {
  readonly observe?: 'body';
};

type HttpClientEventOptions = HttpClientOptions & {
  readonly observe: 'events';
};

type HttpClientResponseOptions = HttpClientOptions & {
  readonly observe: 'response';
};

type HttpClientObserveOptions = HttpClientOptions & {
  readonly observe?: 'body' | 'events' | 'response';
};







@Injectable({ providedIn: 'root' })
export class LlmdexService {
  private readonly http = inject(HttpClient);
/**
 * @summary Health
 */
 healthHealthGet<TData = Health>( options?: HttpClientBodyOptions): Observable<TData>;
 healthHealthGet<TData = Health>( options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 healthHealthGet<TData = Health>( options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  healthHealthGet<TData = Health>(
     options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/health`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/health`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/health`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }

/**
 * Fetch, derive, and write a document. Atomic: it completes or it fails (R1.5).
 * @summary Ingest Model
 */
 ingestModelIngestPost<TData = ModelDoc>(ingestRequest: IngestRequest, options?: HttpClientBodyOptions): Observable<TData>;
 ingestModelIngestPost<TData = ModelDoc>(ingestRequest: IngestRequest, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 ingestModelIngestPost<TData = ModelDoc>(ingestRequest: IngestRequest, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  ingestModelIngestPost<TData = ModelDoc>(
    ingestRequest: IngestRequest, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/ingest`,
      ingestRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/ingest`,
      ingestRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/ingest`,
      ingestRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }

/**
 * @summary List Models
 */
 listModelsModelsGet<TData = ModelDoc[]>( options?: HttpClientBodyOptions): Observable<TData>;
 listModelsModelsGet<TData = ModelDoc[]>( options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 listModelsModelsGet<TData = ModelDoc[]>( options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  listModelsModelsGet<TData = ModelDoc[]>(
     options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/models`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/models`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/models`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }

/**
 * R6.6 - has the upstream card moved since we read it?
 * @summary Model Drift
 */
 modelDriftModelsModelIdDriftGet<TData = DriftReport>(modelId: string, options?: HttpClientBodyOptions): Observable<TData>;
 modelDriftModelsModelIdDriftGet<TData = DriftReport>(modelId: string, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 modelDriftModelsModelIdDriftGet<TData = DriftReport>(modelId: string, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  modelDriftModelsModelIdDriftGet<TData = DriftReport>(
    modelId: string, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/models/${modelId}/drift`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/models/${modelId}/drift`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/models/${modelId}/drift`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }

/**
 * Every field, including the null ones (R6.3).
 * @summary Get Model
 */
 getModelModelsModelIdGet<TData = ModelDoc>(modelId: string, options?: HttpClientBodyOptions): Observable<TData>;
 getModelModelsModelIdGet<TData = ModelDoc>(modelId: string, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 getModelModelsModelIdGet<TData = ModelDoc>(modelId: string, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  getModelModelsModelIdGet<TData = ModelDoc>(
    modelId: string, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/models/${modelId}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/models/${modelId}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/models/${modelId}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }

/**
 * @summary List Benchmarks
 */
 listBenchmarksBenchmarksGet<TData = Benchmark[]>( options?: HttpClientBodyOptions): Observable<TData>;
 listBenchmarksBenchmarksGet<TData = Benchmark[]>( options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 listBenchmarksBenchmarksGet<TData = Benchmark[]>( options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  listBenchmarksBenchmarksGet<TData = Benchmark[]>(
     options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/benchmarks`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/benchmarks`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/benchmarks`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }

/**
 * @summary Get Benchmark
 */
 getBenchmarkBenchmarksSlugGet<TData = Benchmark>(slug: string, options?: HttpClientBodyOptions): Observable<TData>;
 getBenchmarkBenchmarksSlugGet<TData = Benchmark>(slug: string, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 getBenchmarkBenchmarksSlugGet<TData = Benchmark>(slug: string, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  getBenchmarkBenchmarksSlugGet<TData = Benchmark>(
    slug: string, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/benchmarks/${slug}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/benchmarks/${slug}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/benchmarks/${slug}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }

/**
 * Read the card, ask the model to locate facts in it, store what verifies.
 *
 * A run that verifies nothing is a success: most cards state none of this, and
 * an empty result with its rejections is information (R3.2).
 * @summary Extract Model
 */
 extractModelModelsModelIdExtractPost<TData = ModelDoc>(modelId: string, options?: HttpClientBodyOptions): Observable<TData>;
 extractModelModelsModelIdExtractPost<TData = ModelDoc>(modelId: string, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 extractModelModelsModelIdExtractPost<TData = ModelDoc>(modelId: string, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  extractModelModelsModelIdExtractPost<TData = ModelDoc>(
    modelId: string, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/models/${modelId}/extract`,
      undefined,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/models/${modelId}/extract`,
      undefined,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/models/${modelId}/extract`,
      undefined,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }

};

